package sistem.antrian.frames;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author fgroupindonesia
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerFrame
     */
    CardLayout card = null;

    public ClientFrame() {
        initComponents();
        readPoliNames();

        card = (CardLayout) panelMain.getLayout();
    }

    private void switchPanelToSetting() {
        card.show(panelMain, "panelSettings");
    }

    private void switchPanelToWork() {
        card.show(panelMain, "panelWork");
    }

    private void readPoliNames() {

        // clear first
        comboboxPoliName.removeAllItems();

        String nama = this.getClass().getResource("/sistem/antrian/audio/").getPath();
        nama = nama.replaceAll("%20", " ");

        if (radioButtonBahasaIndo.isSelected()) {
            nama += "indonesia/nama-poli.txt";
        } else {
            nama += "english/clinic-name.txt";
        }

        BufferedReader reader;

        try {
            reader = new BufferedReader(new FileReader(nama));
            String line = reader.readLine();

            while (line != null) {
                //System.out.println(line);
                // read next line
                line = reader.readLine();
                comboboxPoliName.addItem(line);
            }

            reader.close();
        } catch (Exception e) {
            //e.printStackTrace();
            System.err.println(e.getMessage());
        }

    }

    private void saveSettings() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonMode = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        labelPoliName = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        comboboxPoliName = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        radioButtonEnglish = new javax.swing.JRadioButton();
        radioButtonBahasaIndo = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Antrian - LOKET");

        panelHeader.setBackground(new java.awt.Color(0, 255, 0));
        panelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelHeader.setPreferredSize(new java.awt.Dimension(500, 75));
        panelHeader.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RUMAH SAKIT MEDIKAKOM");
        panelHeader.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMain.setPreferredSize(new java.awt.Dimension(751, 436));
        panelMain.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LOKET"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(739, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("SAAT INI"));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("A.100");
        jPanel4.add(jLabel2, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("MODE"));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("AKTIF");
        jPanel5.add(jLabel3, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        buttonMode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/warning.png"))); // NOI18N
        buttonMode.setText("Istirahat");
        buttonMode.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel3.add(buttonMode);

        buttonNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/next.png"))); // NOI18N
        buttonNext.setText("Selanjutnya");
        buttonNext.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel3.add(buttonNext);

        buttonSettings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/edit.png"))); // NOI18N
        buttonSettings.setText("Penyetelan");
        buttonSettings.setPreferredSize(new java.awt.Dimension(200, 100));
        buttonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSettingsActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSettings);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("NAMA POLI"));
        jPanel6.setPreferredSize(new java.awt.Dimension(608, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        labelPoliName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelPoliName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPoliName.setText("POLI ANAK");
        jPanel6.add(labelPoliName, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        panelMain.add(jPanel1, "panelWork");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("LOKET"));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(739, 100));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("NAMA POLI"));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel9.setLayout(new java.awt.BorderLayout());

        comboboxPoliName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(comboboxPoliName, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("BAHASA OPERATOR"));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        buttonGroup1.add(radioButtonEnglish);
        radioButtonEnglish.setSelected(true);
        radioButtonEnglish.setText("Bahasa Inggris");
        jPanel10.add(radioButtonEnglish);

        buttonGroup1.add(radioButtonBahasaIndo);
        radioButtonBahasaIndo.setText("Bahasa Indonesia");
        jPanel10.add(radioButtonBahasaIndo);

        jPanel8.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/back.png"))); // NOI18N
        buttonBack.setText("Kembali");
        buttonBack.setPreferredSize(new java.awt.Dimension(200, 100));
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel11.add(buttonBack);

        jPanel7.add(jPanel11, java.awt.BorderLayout.CENTER);

        panelMain.add(jPanel7, "panelSettings");

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        switchPanelToWork();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSettingsActionPerformed
        switchPanelToSetting();
    }//GEN-LAST:event_buttonSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonMode;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JComboBox<String> comboboxPoliName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelPoliName;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JRadioButton radioButtonBahasaIndo;
    private javax.swing.JRadioButton radioButtonEnglish;
    // End of variables declaration//GEN-END:variables

}
