package sistem.antrian.frames;

import sistem.antrian.config.Activator;
import sistem.antrian.config.Keys;
import sistem.antrian.fx.Iconifier;

/**
 * Class ServeMainFramerFrame : used for first running the app
 *
 * @author fgroupindonesia
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Activator act = new Activator(this);

    public MainFrame() {
        initComponents();
        
         new Iconifier(this);
         
        if (!act.isActivated()) {
            lockButtons(true);
        } else {
            lockButtons(false);
        }
    }

    public void lockButtons(boolean b) {
        
            buttonAktifasi.setEnabled(b);
            buttonLoket.setEnabled(!b);
            buttonServer.setEnabled(!b);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonServer = new javax.swing.JButton();
        buttonLoket = new javax.swing.JButton();
        buttonAktifasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Antrian - MAIN FRAME");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("JALANKAN PROGRAM"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        buttonServer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/server.png"))); // NOI18N
        buttonServer.setText("Server");
        buttonServer.setEnabled(false);
        buttonServer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonServer.setPreferredSize(new java.awt.Dimension(200, 100));
        buttonServer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(buttonServer);

        buttonLoket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLoket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/client.png"))); // NOI18N
        buttonLoket.setText("Loket");
        buttonLoket.setEnabled(false);
        buttonLoket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLoket.setPreferredSize(new java.awt.Dimension(200, 100));
        buttonLoket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(buttonLoket);

        buttonAktifasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAktifasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/antrian/images/key.png"))); // NOI18N
        buttonAktifasi.setText("Aktifasi");
        buttonAktifasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAktifasi.setPreferredSize(new java.awt.Dimension(200, 100));
        buttonAktifasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAktifasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAktifasiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAktifasi);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAktifasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAktifasiActionPerformed

        if (act.isActivated()) {
            act.message(Keys.Notification.SUCCESS);
        } else {
            act.request();
        }

    }//GEN-LAST:event_buttonAktifasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAktifasi;
    private javax.swing.JButton buttonLoket;
    private javax.swing.JButton buttonServer;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
