/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistem.antrian.frames;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import sistem.antrian.fx.MarqueeFX;

/**
 *
 * @author staff
 */
public class ServerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public ServerFrame() {
        initComponents();
        showImageMode1();
        animatedNews();
    }

    private void animatedNews() {
        MarqueeFX mFX = new MarqueeFX(labelNewsMode1);
        Timer t = new Timer(400, mFX); // set a timer
        t.start();
    }

    private void showImageMode1() {
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(this.getClass().getResource("/sistem/antrian/images/building.jpg")).getImage().getScaledInstance(labelPictureMode1.getWidth(), labelPictureMode1.getHeight(), Image.SCALE_DEFAULT));
        labelPictureMode1.setIcon(imageIcon);
        labelPictureMode1.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelMode1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelPictureMode1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelNewsMode1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTitleMode1 = new javax.swing.JLabel();
        labelOrderNumMode1 = new javax.swing.JLabel();
        panelMode2 = new javax.swing.JPanel();
        panelMode3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        panelHeader.setBackground(new java.awt.Color(102, 255, 51));
        panelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        panelHeader.setPreferredSize(new java.awt.Dimension(500, 75));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("RUMAH SAKIT MEDIKAKOM");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMain.setLayout(new java.awt.CardLayout());

        panelMode1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(575, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel3.setLayout(new java.awt.BorderLayout());

        labelPictureMode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPictureMode1.setText("picture");
        jPanel3.add(labelPictureMode1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(575, 75));
        jPanel4.setLayout(new java.awt.BorderLayout());

        labelNewsMode1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNewsMode1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNewsMode1.setText("Berita Pengumuman disini ... Ga papa-panjang juga yang penting nongol...!");
        jPanel4.add(labelNewsMode1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        panelMode1.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(575, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        labelTitleMode1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitleMode1.setForeground(new java.awt.Color(51, 0, 255));
        labelTitleMode1.setText("POLI GIGI");
        labelTitleMode1.setPreferredSize(new java.awt.Dimension(400, 44));
        jPanel2.add(labelTitleMode1, java.awt.BorderLayout.WEST);

        labelOrderNumMode1.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        labelOrderNumMode1.setForeground(new java.awt.Color(51, 0, 255));
        labelOrderNumMode1.setText("A.100");
        jPanel2.add(labelOrderNumMode1, java.awt.BorderLayout.EAST);

        panelMode1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        panelMain.add(panelMode1, "panelMode1");

        javax.swing.GroupLayout panelMode2Layout = new javax.swing.GroupLayout(panelMode2);
        panelMode2.setLayout(panelMode2Layout);
        panelMode2Layout.setHorizontalGroup(
            panelMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        panelMode2Layout.setVerticalGroup(
            panelMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        panelMain.add(panelMode2, "panelMode2");

        javax.swing.GroupLayout panelMode3Layout = new javax.swing.GroupLayout(panelMode3);
        panelMode3.setLayout(panelMode3Layout);
        panelMode3Layout.setHorizontalGroup(
            panelMode3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        panelMode3Layout.setVerticalGroup(
            panelMode3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        panelMain.add(panelMode3, "panelMode3");

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelNewsMode1;
    private javax.swing.JLabel labelOrderNumMode1;
    private javax.swing.JLabel labelPictureMode1;
    private javax.swing.JLabel labelTitleMode1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMode1;
    private javax.swing.JPanel panelMode2;
    private javax.swing.JPanel panelMode3;
    // End of variables declaration//GEN-END:variables
}
